# Generated by Django 3.2.5 on 2021-07-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=models.CharField(max_length=400),
        ),
    ]
